# Generated by Django 6.0.2 on 2026-03-14 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
