# Generated by Django 6.0.2 on 2026-03-14 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_applications_applied_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
    ]
