# Generated by Django 6.0.2 on 2026-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_rename_applications_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
