# Generated by Django 6.0.2 on 2026-04-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
