# Generated by Django 6.0.2 on 2026-04-12 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-1000', '201–1000'), ('1000+', '1000+')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default=' '),
            preserve_default=False,
        ),
    ]
